name: Examples CI

on:
  pull_request:

jobs:
  macOS-test:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    - name: macOS build
      run: |
        cd Example
        mkdir -p dd
        xcodebuild -scheme RenderExamples -derivedDataPath ./dd test
    - name: archive test results
      uses: actions/upload-artifact@v4
      with:
        name: xctest-files
        path: dd/Logs/Test/**.xcresult/*
