name: Examples CI

on:
  pull_request:

jobs:
  validate:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    - name: macOS build
      run: cd Examples; xcodebuild -scheme RenderExamples
